// AUTO-GENERATED by scripts/build-site-chrome.js — do not edit manually.
// Run: node scripts/build-site-chrome.js

/** Full nav.html (style + nav + script) injected into pages missing a nav */
export const SITE_NAV_HTML = `<style id="site-nav-css">
/* ─── NAV ─── */
.nav {
  position: fixed; top: 0; left: 0; right: 0; z-index: 100;
  height: 64px; padding: 0 5vw;
  display: flex; align-items: center; justify-content: space-between;
  background: rgba(10,15,44,0.85);
  backdrop-filter: blur(20px);
  border-bottom: 1px solid var(--border);
}
.nav-logo {
  font-family: 'Outfit', sans-serif; font-size: 1.1rem; font-weight: 700;
  color: #fff; display: flex; align-items: center; gap: 10px;
}
.nav-logo-avatar {
  width: 34px; height: 34px; border-radius: 50%;
  overflow: hidden; flex-shrink: 0;
  border: 2px solid var(--accent);
  box-shadow: 0 0 10px rgba(201,168,76,0.35);
}
.nav-logo-avatar img { width: 100%; height: 100%; object-fit: cover; object-position: center top; }
.nav-logo-text { display: flex; flex-direction: column; line-height: 1.1; }
.nav-logo-text strong { font-size: 0.95rem; font-weight: 800; color: #fff; }
.nav-logo-text span { font-size: 0.65rem; font-weight: 500; color: var(--text3); letter-spacing: 0.06em; text-transform: uppercase; }
.nav-right { display: flex; align-items: center; gap: 1.5rem; }
.nav-links { display: flex; align-items: center; gap: 2.5rem; }
.nav-links a { font-size: 0.875rem; font-weight: 500; color: var(--text2); transition: color 0.15s; }
.nav-links a:hover { color: #fff; }
.nav-btn {
  font-size: 0.875rem; font-weight: 600; color: #fff;
  background: var(--accent); padding: 0.5rem 1.25rem;
  border-radius: 8px; transition: opacity 0.15s, transform 0.15s;
}
.nav-btn:hover { opacity: 0.88; transform: translateY(-1px); }
.nav-hamburger {
  display: none; flex-direction: column; gap: 5px; cursor: pointer; padding: 4px;
}
.nav-hamburger span { display: block; width: 22px; height: 2px; background: #fff; border-radius: 2px; }
.mobile-drawer {
  display: none; position: fixed; inset: 0; z-index: 99;
  background: var(--bg); padding: 80px 6vw 40px;
  flex-direction: column; gap: 1.5rem;
}
.mobile-drawer.open { display: flex; }
.mobile-drawer a { font-size: 1.2rem; font-weight: 600; color: #fff; padding: 0.6rem 0; border-bottom: 1px solid var(--border); }
/* ─── NAV SCROLLED ─── */
.nav.scrolled {
  background: rgba(10,15,44,0.97);
  box-shadow: 0 4px 32px rgba(0,0,0,0.4);
}
/* ─── NAV RESPONSIVE ─── */
@media (max-width:1100px) {
  .nav-links { display:none; }
  .nav-right .nav-btn { display:none; }
  .nav-hamburger { display:flex; }
}
</style>
<nav class="nav" id="mainNav">
  <a href="/" class="nav-logo">
    <div class="nav-logo-avatar">
      <img src="/assets/mark-gabrielli.jpg" alt="Mark Gabrielli" onerror="this.parentElement.innerHTML='<span style=\\'display:flex;align-items:center;justify-content:center;width:100%;height:100%;font-family:Outfit,sans-serif;font-weight:900;font-size:1rem;color:#fff;background:var(--accent)\\'>M</span>'" />
    </div>
    <div class="nav-logo-text">
      <strong>Mark Gabrielli</strong>
      <span>Fractional CMO &amp; COO</span>
    </div>
  </a>
  <ul class="nav-links">
    <li><a href="/about">About</a></li>
    <li><a href="/services">Services</a></li>
    <li><a href="/magnet-framework" style="color:var(--accent);font-weight:600;">MAGNET&trade;</a></li>
    <li><a href="/results">Results</a></li>
    <li><a href="/blog">Insights</a></li>
    <li><a href="https://academy.markcmo.com" target="_blank" style="color:var(--accent);">Academy</a></li>
  </ul>
  <div class="nav-right">
    <a href="/book" class="nav-btn">Book a Free Call</a>
  </div>
  <div class="nav-hamburger" id="navHam"><span></span><span></span><span></span></div>
</nav>
<div class="mobile-drawer" id="mobileDrawer">
  <a href="/about">About</a>
  <a href="/services">Services</a>
  <a href="/magnet-framework" style="color:var(--accent);font-weight:600;">MAGNET Framework&trade;</a>
  <a href="/results">Results</a>
  <a href="/blog">Insights</a>
  <a href="https://academy.markcmo.com" target="_blank">Academy</a>
  <a href="/book" style="color:var(--accent);font-weight:700;">Book a Free Strategy Call &rarr;</a>
</div>
<script>
(function(){
  var nav=document.getElementById('mainNav');
  if(nav) window.addEventListener('scroll',function(){nav.classList.toggle('scrolled',window.scrollY>20);},{passive:true});
  var ham=document.getElementById('navHam');
  var drawer=document.getElementById('mobileDrawer');
  if(ham&&drawer){
    ham.addEventListener('click',function(){drawer.classList.toggle('open');});
    drawer.querySelectorAll('a').forEach(function(a){a.addEventListener('click',function(){drawer.classList.remove('open');});});
  }
})();
</script>
`;

/** Full footer.html (style + footer) injected into pages missing any footer */
export const SITE_FOOTER_HTML = `<style id="site-footer-css">
/* ─── FOOTER ─── */
footer {
  background: var(--bg2, #0A1628);
  border-top: 1px solid var(--border, rgba(255,255,255,0.08));
}

/* ── Main nav grid ── */
.footer-main {
  max-width: 1400px;
  margin: 0 auto;
  padding: 4rem clamp(1.5rem,6vw,6rem) 2.5rem;
  display: grid;
  grid-template-columns: 2.2fr 1fr 1fr 1fr 1fr 1fr;
  gap: 2.5rem;
}

/* Brand column */
.footer-brand {}
.footer-logo-text {
  font-family: 'Outfit', sans-serif;
  font-size: 1.15rem; font-weight: 800;
  color: #fff; margin-bottom: 0.75rem;
}
.footer-logo-text span { color: var(--accent, #C9A84C); }
.footer-about {
  font-size: 0.825rem; line-height: 1.75;
  color: var(--text3, rgba(255,255,255,0.45));
  margin-bottom: 1.25rem; max-width: 300px;
}
.footer-chips { display: flex; flex-wrap: wrap; gap: 0.4rem; margin-bottom: 1.25rem; }
.footer-chip {
  font-size: 0.63rem; font-weight: 600; letter-spacing: 0.07em;
  text-transform: uppercase; color: var(--text3, rgba(255,255,255,0.45));
  border: 1px solid var(--border, rgba(255,255,255,0.08));
  padding: 0.25rem 0.65rem; border-radius: 4px;
}
.footer-socials { display: flex; gap: 0.5rem; }
.footer-soc {
  width: 34px; height: 34px; border-radius: 8px;
  background: var(--bg3, rgba(255,255,255,0.05));
  border: 1px solid var(--border, rgba(255,255,255,0.08));
  color: var(--text3, rgba(255,255,255,0.45));
  display: flex; align-items: center; justify-content: center;
  font-size: 0.8rem; font-weight: 700; transition: all 0.15s;
  text-decoration: none;
}
.footer-soc:hover { background: var(--accent, #C9A84C); border-color: var(--accent, #C9A84C); color: #0A1628; }

/* Nav columns */
.footer-col h4 {
  font-size: 0.68rem; font-weight: 700; letter-spacing: 0.13em;
  text-transform: uppercase; color: var(--text3, rgba(255,255,255,0.45));
  margin-bottom: 1rem;
}
.footer-col ul { display: flex; flex-direction: column; gap: 0.55rem; list-style: none; padding: 0; margin: 0; }
.footer-col ul li a {
  font-size: 0.8125rem; color: var(--text3, rgba(255,255,255,0.45));
  transition: color 0.15s; text-decoration: none;
}
.footer-col ul li a:hover { color: #fff; }

/* ── Shared horizontal band styles ── */
.footer-services-band,
.footer-glossary-band {
  border-top: 1px solid var(--border, rgba(255,255,255,0.08));
  padding: 1.75rem clamp(1.5rem,6vw,6rem);
  max-width: 1400px; margin: 0 auto;
}
.footer-band-label {
  font-size: 0.65rem; font-weight: 700; letter-spacing: 0.14em;
  text-transform: uppercase; color: var(--text3, rgba(255,255,255,0.35));
  margin-bottom: 0.85rem;
}
.footer-tag-row {
  display: flex; flex-wrap: wrap; gap: 0.45rem;
}
.footer-tag {
  font-size: 0.775rem;
  color: var(--text3, rgba(255,255,255,0.5));
  background: var(--bg3, rgba(255,255,255,0.04));
  border: 1px solid var(--border, rgba(255,255,255,0.08));
  padding: 0.3rem 0.8rem; border-radius: 100px;
  transition: all 0.15s; text-decoration: none; white-space: nowrap;
}
.footer-tag:hover {
  color: #fff;
  border-color: rgba(255,255,255,0.2);
  background: rgba(255,255,255,0.07);
}
.footer-tag.accent {
  color: var(--accent, #C9A84C);
  border-color: rgba(201,168,76,0.3);
  background: rgba(201,168,76,0.05);
}
.footer-tag.accent:hover {
  background: rgba(201,168,76,0.12);
  border-color: rgba(201,168,76,0.55);
}

/* ── Bottom bar ── */
.footer-bar {
  border-top: 1px solid var(--border, rgba(255,255,255,0.08));
  padding: 1.25rem clamp(1.5rem,6vw,6rem);
  max-width: 1400px; margin: 0 auto;
  display: flex; justify-content: space-between; align-items: center;
  flex-wrap: wrap; gap: 0.5rem;
}
.footer-copy { font-size: 0.78rem; color: var(--text3, rgba(255,255,255,0.35)); }
.footer-bar-links { display: flex; gap: 1.25rem; flex-wrap: wrap; }
.footer-bar-links a {
  font-size: 0.78rem; color: var(--text3, rgba(255,255,255,0.35));
  transition: color 0.15s; text-decoration: none;
}
.footer-bar-links a:hover { color: #fff; }

/* ── Responsive ── */
@media (max-width: 1100px) {
  .footer-main { grid-template-columns: 1fr 1fr 1fr 1fr; }
  .footer-brand { grid-column: span 4; }
}
@media (max-width: 900px) {
  .footer-main { grid-template-columns: 1fr 1fr 1fr; }
  .footer-brand { grid-column: span 3; }
}
@media (max-width: 600px) {
  .footer-main { grid-template-columns: 1fr 1fr; }
  .footer-brand { grid-column: span 2; }
  .footer-tag { font-size: 0.72rem; padding: 0.25rem 0.65rem; }
}
</style>

<footer>
  <!-- ── Main nav columns ── -->
  <div class="footer-main">
    <div class="footer-brand">
      <div class="footer-logo-text">Mark <span>Gabrielli</span></div>
      <p class="footer-about">Fractional CMO, COO &amp; Executive Consultant. I help businesses from $1M to $100M find what's broken, build what scales, and execute what others only talk about.</p>
      <div class="footer-chips">
        <span class="footer-chip">WETYR Founder</span>
        <span class="footer-chip">Fractional C-Suite</span>
        <span class="footer-chip">AI Strategist</span>
        <span class="footer-chip">CST Certified</span>
      </div>
      <div class="footer-socials">
        <a href="https://www.linkedin.com/in/marklgabrielli/" target="_blank" rel="noopener" class="footer-soc">in</a>
        <a href="mailto:mark@markcmo.com" class="footer-soc">@</a>
      </div>
    </div>

    <div class="footer-col">
      <h4>C-Suite</h4>
      <ul>
        <li><a href="/fractional-cmo">Fractional CMO</a></li>
        <li><a href="/fractional-coo">Fractional COO</a></li>
        <li><a href="/fractional-ceo">Fractional CEO</a></li>
        <li><a href="/fractional-cto">Fractional CTO</a></li>
        <li><a href="/fractional-cfo">Fractional CFO</a></li>
        <li><a href="/executive-advisory">Executive Advisory</a></li>
        <li><a href="/services">All Services</a></li>
      </ul>
    </div>

    <div class="footer-col">
      <h4>Compare</h4>
      <ul>
        <li><a href="/fractional-cmo-cost">CMO Cost Guide</a></li>
        <li><a href="/compare/fractional-cmo-vs-full-time-cmo/">vs Full-Time CMO</a></li>
        <li><a href="/compare/fractional-cmo-vs-marketing-agency/">vs Agency</a></li>
        <li><a href="/compare/fractional-cmo-vs-vp-of-marketing/">vs VP Marketing</a></li>
        <li><a href="/compare/fractional-cmo-vs-consultant/">vs Consultant</a></li>
        <li><a href="/compare/fractional-cmo-vs-interim-cmo/">vs Interim CMO</a></li>
        <li><a href="/chief-outsiders-alternative">Chief Outsiders Alt.</a></li>
      </ul>
    </div>

    <div class="footer-col">
      <h4>By Stage</h4>
      <ul>
        <li><a href="/fractional-cmo-pre-revenue">Pre-Revenue</a></li>
        <li><a href="/fractional-cmo-series-a">Series A</a></li>
        <li><a href="/fractional-cmo-series-b">Series B</a></li>
        <li><a href="/fractional-cmo-bootstrapped-companies">Bootstrapped</a></li>
        <li><a href="/fractional-cmo-pe-backed-companies">PE-Backed</a></li>
        <li><a href="/fractional-cmo-venture-capital">VC-Backed</a></li>
        <li><a href="/best-fractional-cmo">Best Fractional CMO</a></li>
      </ul>
    </div>

    <div class="footer-col">
      <h4>Industries</h4>
      <ul>
        <li><a href="/fractional-cmo-saas">SaaS</a></li>
        <li><a href="/fractional-cmo-healthcare">Healthcare</a></li>
        <li><a href="/fractional-cmo-fintech">Fintech</a></li>
        <li><a href="/fractional-cmo-ai">AI Companies</a></li>
        <li><a href="/fractional-cmo-b2b">B2B</a></li>
        <li><a href="/fractional-cmo-ecommerce">eCommerce</a></li>
        <li><a href="/industries">All Industries</a></li>
      </ul>
    </div>

    <div class="footer-col">
      <h4>Learn</h4>
      <ul>
        <li><a href="/magnet-framework" style="color:var(--accent,#C9A84C);font-weight:600;">MAGNET Framework&trade;</a></li>
        <li><a href="/blog">Insights &amp; Blog</a></li>
        <li><a href="/about">About Mark</a></li>
        <li><a href="/testimonials">Testimonials</a></li>
        <li><a href="/faq">FAQ</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="https://academy.markcmo.com" target="_blank" style="color:var(--accent,#C9A84C);font-weight:600;">Academy ↗</a></li>
      </ul>
    </div>
  </div>

  <!-- ── Horizontal marketing services strip ── -->
  <div class="footer-services-band">
    <div class="footer-band-label">Marketing Services</div>
    <div class="footer-tag-row">
      <a href="/demand-generation" class="footer-tag">Demand Generation</a>
      <a href="/lead-generation" class="footer-tag">Lead Generation</a>
      <a href="/b2b-marketing" class="footer-tag">B2B Marketing</a>
      <a href="/content-marketing" class="footer-tag">Content Marketing</a>
      <a href="/email-marketing" class="footer-tag">Email Marketing</a>
      <a href="/digital-marketing" class="footer-tag">Digital Marketing</a>
      <a href="/social-media-marketing" class="footer-tag">Social Media Marketing</a>
      <a href="/linkedin-marketing" class="footer-tag">LinkedIn Marketing</a>
      <a href="/paid-social" class="footer-tag">Paid Social</a>
      <a href="/ppc-management" class="footer-tag">PPC Management</a>
      <a href="/local-seo" class="footer-tag">Local SEO</a>
      <a href="/crm-automation" class="footer-tag">CRM Automation</a>
      <a href="/marketing-automation" class="footer-tag">Marketing Automation</a>
      <a href="/account-based-marketing" class="footer-tag">Account-Based Marketing</a>
      <a href="/go-to-market-strategy" class="footer-tag">Go-to-Market Strategy</a>
      <a href="/marketing-audit" class="footer-tag">Marketing Audit</a>
      <a href="/marketing-strategy" class="footer-tag">Marketing Strategy</a>
      <a href="/revenue-operations" class="footer-tag">Revenue Operations</a>
      <a href="/brand-strategy" class="footer-tag">Brand Strategy</a>
      <a href="/performance-marketing" class="footer-tag">Performance Marketing</a>
    </div>
  </div>

  <!-- ── Horizontal glossary strip ── -->
  <div class="footer-glossary-band">
    <div class="footer-band-label">Glossary &amp; Resources</div>
    <div class="footer-tag-row">
      <a href="/what-is-a-fractional-cmo" class="footer-tag accent">What is a Fractional CMO?</a>
      <a href="/what-is-demand-generation" class="footer-tag">What is Demand Generation?</a>
      <a href="/what-is-b2b-marketing" class="footer-tag">What is B2B Marketing?</a>
      <a href="/what-is-go-to-market-strategy" class="footer-tag">What is GTM Strategy?</a>
      <a href="/what-is-revenue-operations" class="footer-tag">What is RevOps?</a>
      <a href="/what-is-account-based-marketing" class="footer-tag">What is ABM?</a>
      <a href="/what-is-marketing-automation" class="footer-tag">What is Marketing Automation?</a>
      <a href="/what-is-customer-acquisition-cost" class="footer-tag">What is CAC?</a>
      <a href="/what-is-marketing-qualified-lead" class="footer-tag">What is MQL?</a>
      <a href="/what-is-ideal-customer-profile" class="footer-tag">What is ICP?</a>
      <a href="/what-is-content-marketing" class="footer-tag">What is Content Marketing?</a>
      <a href="/what-is-lead-generation" class="footer-tag">What is Lead Generation?</a>
      <a href="/fractional-cmo-roi-calculator" class="footer-tag accent">ROI Calculator</a>
      <a href="/marketing-assessment" class="footer-tag accent">Free Assessment</a>
      <a href="/fractional-cmo-near-me" class="footer-tag">CMO Near Me</a>
      <a href="/cities" class="footer-tag">All Cities</a>
      <a href="/states" class="footer-tag">All States</a>
    </div>
  </div>

  <!-- ── Bottom bar ── -->
  <div class="footer-bar">
    <span class="footer-copy">&copy; 2026 Mark Gabrielli &middot; markcmo.com &middot; All rights reserved.</span>
    <div class="footer-bar-links">
      <a href="https://www.linkedin.com/in/marklgabrielli/" target="_blank" rel="noopener">LinkedIn</a>
      <a href="https://x.com/markgcmo" target="_blank" rel="noopener">X / Twitter</a>
      <a href="https://medium.com/@mark_louis_gabrielli_jr" target="_blank" rel="noopener">Medium</a>
      <a href="https://www.tiktok.com/@mark.gabrielli.cmo" target="_blank" rel="noopener">TikTok</a>
    </div>
  </div>
</footer>
`;

/** Just the <footer>…</footer> element — used to REPLACE old footer-mega blocks */
export const SITE_FOOTER_ELEMENT = `<footer>
  <!-- ── Main nav columns ── -->
  <div class="footer-main">
    <div class="footer-brand">
      <div class="footer-logo-text">Mark <span>Gabrielli</span></div>
      <p class="footer-about">Fractional CMO, COO &amp; Executive Consultant. I help businesses from $1M to $100M find what's broken, build what scales, and execute what others only talk about.</p>
      <div class="footer-chips">
        <span class="footer-chip">WETYR Founder</span>
        <span class="footer-chip">Fractional C-Suite</span>
        <span class="footer-chip">AI Strategist</span>
        <span class="footer-chip">CST Certified</span>
      </div>
      <div class="footer-socials">
        <a href="https://www.linkedin.com/in/marklgabrielli/" target="_blank" rel="noopener" class="footer-soc">in</a>
        <a href="mailto:mark@markcmo.com" class="footer-soc">@</a>
      </div>
    </div>

    <div class="footer-col">
      <h4>C-Suite</h4>
      <ul>
        <li><a href="/fractional-cmo">Fractional CMO</a></li>
        <li><a href="/fractional-coo">Fractional COO</a></li>
        <li><a href="/fractional-ceo">Fractional CEO</a></li>
        <li><a href="/fractional-cto">Fractional CTO</a></li>
        <li><a href="/fractional-cfo">Fractional CFO</a></li>
        <li><a href="/executive-advisory">Executive Advisory</a></li>
        <li><a href="/services">All Services</a></li>
      </ul>
    </div>

    <div class="footer-col">
      <h4>Compare</h4>
      <ul>
        <li><a href="/fractional-cmo-cost">CMO Cost Guide</a></li>
        <li><a href="/compare/fractional-cmo-vs-full-time-cmo/">vs Full-Time CMO</a></li>
        <li><a href="/compare/fractional-cmo-vs-marketing-agency/">vs Agency</a></li>
        <li><a href="/compare/fractional-cmo-vs-vp-of-marketing/">vs VP Marketing</a></li>
        <li><a href="/compare/fractional-cmo-vs-consultant/">vs Consultant</a></li>
        <li><a href="/compare/fractional-cmo-vs-interim-cmo/">vs Interim CMO</a></li>
        <li><a href="/chief-outsiders-alternative">Chief Outsiders Alt.</a></li>
      </ul>
    </div>

    <div class="footer-col">
      <h4>By Stage</h4>
      <ul>
        <li><a href="/fractional-cmo-pre-revenue">Pre-Revenue</a></li>
        <li><a href="/fractional-cmo-series-a">Series A</a></li>
        <li><a href="/fractional-cmo-series-b">Series B</a></li>
        <li><a href="/fractional-cmo-bootstrapped-companies">Bootstrapped</a></li>
        <li><a href="/fractional-cmo-pe-backed-companies">PE-Backed</a></li>
        <li><a href="/fractional-cmo-venture-capital">VC-Backed</a></li>
        <li><a href="/best-fractional-cmo">Best Fractional CMO</a></li>
      </ul>
    </div>

    <div class="footer-col">
      <h4>Industries</h4>
      <ul>
        <li><a href="/fractional-cmo-saas">SaaS</a></li>
        <li><a href="/fractional-cmo-healthcare">Healthcare</a></li>
        <li><a href="/fractional-cmo-fintech">Fintech</a></li>
        <li><a href="/fractional-cmo-ai">AI Companies</a></li>
        <li><a href="/fractional-cmo-b2b">B2B</a></li>
        <li><a href="/fractional-cmo-ecommerce">eCommerce</a></li>
        <li><a href="/industries">All Industries</a></li>
      </ul>
    </div>

    <div class="footer-col">
      <h4>Learn</h4>
      <ul>
        <li><a href="/magnet-framework" style="color:var(--accent,#C9A84C);font-weight:600;">MAGNET Framework&trade;</a></li>
        <li><a href="/blog">Insights &amp; Blog</a></li>
        <li><a href="/about">About Mark</a></li>
        <li><a href="/testimonials">Testimonials</a></li>
        <li><a href="/faq">FAQ</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="https://academy.markcmo.com" target="_blank" style="color:var(--accent,#C9A84C);font-weight:600;">Academy ↗</a></li>
      </ul>
    </div>
  </div>

  <!-- ── Horizontal marketing services strip ── -->
  <div class="footer-services-band">
    <div class="footer-band-label">Marketing Services</div>
    <div class="footer-tag-row">
      <a href="/demand-generation" class="footer-tag">Demand Generation</a>
      <a href="/lead-generation" class="footer-tag">Lead Generation</a>
      <a href="/b2b-marketing" class="footer-tag">B2B Marketing</a>
      <a href="/content-marketing" class="footer-tag">Content Marketing</a>
      <a href="/email-marketing" class="footer-tag">Email Marketing</a>
      <a href="/digital-marketing" class="footer-tag">Digital Marketing</a>
      <a href="/social-media-marketing" class="footer-tag">Social Media Marketing</a>
      <a href="/linkedin-marketing" class="footer-tag">LinkedIn Marketing</a>
      <a href="/paid-social" class="footer-tag">Paid Social</a>
      <a href="/ppc-management" class="footer-tag">PPC Management</a>
      <a href="/local-seo" class="footer-tag">Local SEO</a>
      <a href="/crm-automation" class="footer-tag">CRM Automation</a>
      <a href="/marketing-automation" class="footer-tag">Marketing Automation</a>
      <a href="/account-based-marketing" class="footer-tag">Account-Based Marketing</a>
      <a href="/go-to-market-strategy" class="footer-tag">Go-to-Market Strategy</a>
      <a href="/marketing-audit" class="footer-tag">Marketing Audit</a>
      <a href="/marketing-strategy" class="footer-tag">Marketing Strategy</a>
      <a href="/revenue-operations" class="footer-tag">Revenue Operations</a>
      <a href="/brand-strategy" class="footer-tag">Brand Strategy</a>
      <a href="/performance-marketing" class="footer-tag">Performance Marketing</a>
    </div>
  </div>

  <!-- ── Horizontal glossary strip ── -->
  <div class="footer-glossary-band">
    <div class="footer-band-label">Glossary &amp; Resources</div>
    <div class="footer-tag-row">
      <a href="/what-is-a-fractional-cmo" class="footer-tag accent">What is a Fractional CMO?</a>
      <a href="/what-is-demand-generation" class="footer-tag">What is Demand Generation?</a>
      <a href="/what-is-b2b-marketing" class="footer-tag">What is B2B Marketing?</a>
      <a href="/what-is-go-to-market-strategy" class="footer-tag">What is GTM Strategy?</a>
      <a href="/what-is-revenue-operations" class="footer-tag">What is RevOps?</a>
      <a href="/what-is-account-based-marketing" class="footer-tag">What is ABM?</a>
      <a href="/what-is-marketing-automation" class="footer-tag">What is Marketing Automation?</a>
      <a href="/what-is-customer-acquisition-cost" class="footer-tag">What is CAC?</a>
      <a href="/what-is-marketing-qualified-lead" class="footer-tag">What is MQL?</a>
      <a href="/what-is-ideal-customer-profile" class="footer-tag">What is ICP?</a>
      <a href="/what-is-content-marketing" class="footer-tag">What is Content Marketing?</a>
      <a href="/what-is-lead-generation" class="footer-tag">What is Lead Generation?</a>
      <a href="/fractional-cmo-roi-calculator" class="footer-tag accent">ROI Calculator</a>
      <a href="/marketing-assessment" class="footer-tag accent">Free Assessment</a>
      <a href="/fractional-cmo-near-me" class="footer-tag">CMO Near Me</a>
      <a href="/cities" class="footer-tag">All Cities</a>
      <a href="/states" class="footer-tag">All States</a>
    </div>
  </div>

  <!-- ── Bottom bar ── -->
  <div class="footer-bar">
    <span class="footer-copy">&copy; 2026 Mark Gabrielli &middot; markcmo.com &middot; All rights reserved.</span>
    <div class="footer-bar-links">
      <a href="https://www.linkedin.com/in/marklgabrielli/" target="_blank" rel="noopener">LinkedIn</a>
      <a href="https://x.com/markgcmo" target="_blank" rel="noopener">X / Twitter</a>
      <a href="https://medium.com/@mark_louis_gabrielli_jr" target="_blank" rel="noopener">Medium</a>
      <a href="https://www.tiktok.com/@mark.gabrielli.cmo" target="_blank" rel="noopener">TikTok</a>
    </div>
  </div>
</footer>`;
