// AUTO-GENERATED by scripts/build-site-chrome.js — do not edit manually.
// Run: node scripts/build-site-chrome.js

/** Full nav.html (style + nav + script) injected into pages missing a nav */
export const SITE_NAV_HTML = `<style id="site-nav-css">
/* ─── NAV ─── */
.nav {
  position: fixed; top: 0; left: 0; right: 0; z-index: 100;
  height: 64px; padding: 0 5vw;
  display: flex; align-items: center; justify-content: space-between;
  background: rgba(10,15,44,0.85);
  backdrop-filter: blur(20px);
  border-bottom: 1px solid var(--border);
}
.nav-logo {
  font-family: 'Outfit', sans-serif; font-size: 1.1rem; font-weight: 700;
  color: #fff; display: flex; align-items: center; gap: 10px;
}
.nav-logo-avatar {
  width: 34px; height: 34px; border-radius: 50%;
  overflow: hidden; flex-shrink: 0;
  border: 2px solid var(--accent);
  box-shadow: 0 0 10px rgba(201,168,76,0.35);
}
.nav-logo-avatar img { width: 100%; height: 100%; object-fit: cover; object-position: center top; }
.nav-logo-text { display: flex; flex-direction: column; line-height: 1.1; }
.nav-logo-text strong { font-size: 0.95rem; font-weight: 800; color: #fff; }
.nav-logo-text span { font-size: 0.65rem; font-weight: 500; color: var(--text3); letter-spacing: 0.06em; text-transform: uppercase; }
.nav-right { display: flex; align-items: center; gap: 1.5rem; }
.nav-links { display: flex; align-items: center; gap: 2.5rem; }
.nav-links a { font-size: 0.875rem; font-weight: 500; color: var(--text2); transition: color 0.15s; }
.nav-links a:hover { color: #fff; }
.nav-btn {
  font-size: 0.875rem; font-weight: 600; color: #fff;
  background: var(--accent); padding: 0.5rem 1.25rem;
  border-radius: 8px; transition: opacity 0.15s, transform 0.15s;
}
.nav-btn:hover { opacity: 0.88; transform: translateY(-1px); }
.nav-hamburger {
  display: none; flex-direction: column; gap: 5px; cursor: pointer; padding: 4px;
}
.nav-hamburger span { display: block; width: 22px; height: 2px; background: #fff; border-radius: 2px; }
.mobile-drawer {
  display: none; position: fixed; inset: 0; z-index: 99;
  background: var(--bg); padding: 80px 6vw 40px;
  flex-direction: column; gap: 1.5rem;
}
.mobile-drawer.open { display: flex; }
.mobile-drawer a { font-size: 1.2rem; font-weight: 600; color: #fff; padding: 0.6rem 0; border-bottom: 1px solid var(--border); }
/* ─── NAV SCROLLED ─── */
.nav.scrolled {
  background: rgba(10,15,44,0.97);
  box-shadow: 0 4px 32px rgba(0,0,0,0.4);
}
/* ─── NAV RESPONSIVE ─── */
@media (max-width:1100px) {
  .nav-links { display:none; }
  .nav-right .nav-btn { display:none; }
  .nav-hamburger { display:flex; }
}
</style>
<nav class="nav" id="mainNav">
  <a href="/" class="nav-logo">
    <div class="nav-logo-avatar">
      <img src="/assets/mark-gabrielli.jpg" alt="Mark Gabrielli" onerror="this.parentElement.innerHTML='<span style=\\'display:flex;align-items:center;justify-content:center;width:100%;height:100%;font-family:Outfit,sans-serif;font-weight:900;font-size:1rem;color:#fff;background:var(--accent)\\'>M</span>'" />
    </div>
    <div class="nav-logo-text">
      <strong>Mark Gabrielli</strong>
      <span>Fractional CMO &amp; COO</span>
    </div>
  </a>
  <ul class="nav-links">
    <li><a href="/about">About</a></li>
    <li><a href="/services">Services</a></li>
    <li><a href="/magnet-framework" style="color:var(--accent);font-weight:600;">MAGNET&trade;</a></li>
    <li><a href="/results">Results</a></li>
    <li><a href="/blog">Insights</a></li>
    <li><a href="https://academy.markcmo.com" target="_blank" style="color:var(--accent);">Academy</a></li>
  </ul>
  <div class="nav-right">
    <a href="/book" class="nav-btn">Book a Free Call</a>
  </div>
  <div class="nav-hamburger" id="navHam"><span></span><span></span><span></span></div>
</nav>
<div class="mobile-drawer" id="mobileDrawer">
  <a href="/about">About</a>
  <a href="/services">Services</a>
  <a href="/magnet-framework" style="color:var(--accent);font-weight:600;">MAGNET Framework&trade;</a>
  <a href="/results">Results</a>
  <a href="/blog">Insights</a>
  <a href="https://academy.markcmo.com" target="_blank">Academy</a>
  <a href="/book" style="color:var(--accent);font-weight:700;">Book a Free Strategy Call &rarr;</a>
</div>
<script>
(function(){
  var nav=document.getElementById('mainNav');
  if(nav) window.addEventListener('scroll',function(){nav.classList.toggle('scrolled',window.scrollY>20);},{passive:true});
  var ham=document.getElementById('navHam');
  var drawer=document.getElementById('mobileDrawer');
  if(ham&&drawer){
    ham.addEventListener('click',function(){drawer.classList.toggle('open');});
    drawer.querySelectorAll('a').forEach(function(a){a.addEventListener('click',function(){drawer.classList.remove('open');});});
  }
})();
</script>
`;

/** Full footer.html (style + footer) injected into pages missing any footer */
export const SITE_FOOTER_HTML = `<style id="site-footer-css">
/* ─── FOOTER — self-contained, matches homepage exactly ─── */
footer {
  /* CSS variable fallbacks so footer works even without style.css */
  --f-bg:     #050919;
  --f-bg3:    #0E1438;
  --f-border: rgba(255,255,255,0.08);
  --f-accent: #C9A84C;
  --f-text3:  rgba(255,255,255,0.40);
  background: var(--bg2, #050919);
  border-top: 1px solid var(--border, rgba(255,255,255,0.08));
  /* Resets to cancel any global footer overrides */
  border-radius: 0;
  margin-top: 0;
  padding: 0;
  position: static;
}
footer::before { display: none; content: none; }
.footer-main {
  max-width: 1400px; margin: 0 auto;
  padding: 4rem clamp(1.5rem,6vw,6rem) 3rem;
  display: grid;
  grid-template-columns: 2fr repeat(7,1fr);
  gap: 2rem;
}
.footer-logo-text {
  font-family: 'Outfit',sans-serif; font-size: 1.1rem; font-weight: 800;
  color: #fff; margin-bottom: 0.75rem;
}
.footer-logo-text span { color: var(--accent, #C9A84C); }
.footer-about {
  font-size: 0.825rem; line-height: 1.7;
  color: var(--text3, rgba(255,255,255,0.40)); margin-bottom: 1.25rem;
}
.footer-chips { display: flex; flex-wrap: wrap; gap: 0.4rem; margin-bottom: 1.25rem; }
.footer-chip {
  font-size: 0.65rem; font-weight: 600; letter-spacing: 0.06em;
  text-transform: uppercase; color: var(--text3, rgba(255,255,255,0.40));
  border: 1px solid var(--border, rgba(255,255,255,0.08));
  padding: 0.25rem 0.6rem; border-radius: 4px;
}
.footer-socials { display: flex; gap: 0.6rem; }
.footer-soc {
  width: 34px; height: 34px; border-radius: 8px;
  background: var(--bg3, #0E1438);
  border: 1px solid var(--border, rgba(255,255,255,0.08));
  color: var(--text3, rgba(255,255,255,0.40));
  display: flex; align-items: center; justify-content: center;
  font-size: 0.8rem; font-weight: 700; transition: all 0.15s;
  text-decoration: none;
}
.footer-soc:hover { background: var(--accent, #C9A84C); border-color: var(--accent, #C9A84C); color: #fff; }
.footer-col h4 {
  font-size: 0.7rem; font-weight: 700; letter-spacing: 0.12em;
  text-transform: uppercase; color: var(--text3, rgba(255,255,255,0.40));
  margin-bottom: 1rem;
}
.footer-col ul {
  display: flex; flex-direction: column; gap: 0.6rem;
  list-style: none; padding: 0; margin: 0;
}
.footer-col ul li a {
  font-size: 0.8125rem; color: var(--text3, rgba(255,255,255,0.40));
  transition: color 0.15s; text-decoration: none;
}
.footer-col ul li a:hover { color: #fff; }
.footer-bar {
  border-top: 1px solid var(--border, rgba(255,255,255,0.08));
  padding: 1.5rem clamp(1.5rem,6vw,6rem);
  max-width: 1400px; margin: 0 auto;
  display: flex; justify-content: space-between; align-items: center;
  flex-wrap: wrap; gap: 0.5rem;
}
.footer-copy { font-size: 0.8rem; color: var(--text3, rgba(255,255,255,0.40)); }
.footer-bar-links { display: flex; gap: 1.25rem; flex-wrap: wrap; }
.footer-bar-links a {
  font-size: 0.8rem; color: var(--text3, rgba(255,255,255,0.40));
  transition: color 0.15s; text-decoration: none;
}
.footer-bar-links a:hover { color: #fff; }
@media (max-width:1100px) {
  .footer-main { grid-template-columns: 1fr 1fr 1fr 1fr; }
  .footer-brand { grid-column: span 4; }
}
@media (max-width:900px) {
  .footer-main { grid-template-columns: 1fr 1fr 1fr; }
  .footer-brand { grid-column: span 3; }
}
@media (max-width:600px) {
  .footer-main { grid-template-columns: 1fr 1fr; }
  .footer-brand { grid-column: span 2; }
}
</style>

<footer>
  <div class="footer-main">
    <div class="footer-brand">
      <div class="footer-logo-text">Mark <span>Gabrielli</span></div>
      <p class="footer-about">Fractional CMO, COO &amp; Executive Consultant. I help businesses from $1M to $100M find what&rsquo;s broken, build what scales, and execute what others only talk about.</p>
      <div class="footer-chips">
        <span class="footer-chip">WETYR Founder</span>
        <span class="footer-chip">Fractional C-Suite</span>
        <span class="footer-chip">AI Strategist</span>
        <span class="footer-chip">CST Certified</span>
      </div>
      <div class="footer-socials">
        <a href="https://www.linkedin.com/in/marklgabrielli/" target="_blank" rel="noopener" class="footer-soc">in</a>
        <a href="mailto:mark@markcmo.com" class="footer-soc">@</a>
      </div>
    </div>

    <div class="footer-col"><h4>C-Suite</h4><ul>
      <li><a href="/fractional-cmo">Fractional CMO</a></li>
      <li><a href="/fractional-coo">Fractional COO</a></li>
      <li><a href="/fractional-ceo">Fractional CEO</a></li>
      <li><a href="/fractional-cto">Fractional CTO</a></li>
      <li><a href="/fractional-cfo">Fractional CFO</a></li>
      <li><a href="/executive-advisory">Executive Advisory</a></li>
      <li><a href="/services">All Services</a></li>
    </ul></div>

    <div class="footer-col"><h4>Marketing</h4><ul>
      <li><a href="/demand-generation">Demand Generation</a></li>
      <li><a href="/lead-generation">Lead Generation</a></li>
      <li><a href="/b2b-marketing">B2B Marketing</a></li>
      <li><a href="/content-marketing">Content Marketing</a></li>
      <li><a href="/email-marketing">Email Marketing</a></li>
      <li><a href="/digital-marketing">Digital Marketing</a></li>
      <li><a href="/social-media-marketing">Social Media</a></li>
      <li><a href="/linkedin-marketing">LinkedIn Marketing</a></li>
      <li><a href="/paid-social">Paid Social</a></li>
      <li><a href="/ppc-management">PPC Management</a></li>
      <li><a href="/local-seo">Local SEO</a></li>
      <li><a href="/crm-automation">CRM Automation</a></li>
      <li><a href="/marketing-automation">Marketing Automation</a></li>
      <li><a href="/account-based-marketing">ABM</a></li>
      <li><a href="/go-to-market-strategy">Go-to-Market</a></li>
      <li><a href="/marketing-strategy">Marketing Strategy</a></li>
    </ul></div>

    <div class="footer-col"><h4>Compare</h4><ul>
      <li><a href="/fractional-cmo-cost">CMO Cost</a></li>
      <li><a href="/compare/fractional-cmo-vs-full-time-cmo/">vs Full-Time CMO</a></li>
      <li><a href="/compare/fractional-cmo-vs-marketing-agency/">vs Agency</a></li>
      <li><a href="/compare/fractional-cmo-vs-vp-of-marketing/">vs VP of Marketing</a></li>
      <li><a href="/compare/fractional-cmo-vs-consultant/">vs Consultant</a></li>
      <li><a href="/compare/fractional-cmo-vs-interim-cmo/">vs Interim CMO</a></li>
      <li><a href="/chief-outsiders-alternative">Chief Outsiders Alt.</a></li>
    </ul></div>

    <div class="footer-col"><h4>By Stage</h4><ul>
      <li><a href="/fractional-cmo-pre-revenue">Pre-Revenue</a></li>
      <li><a href="/fractional-cmo-series-a">Series A</a></li>
      <li><a href="/fractional-cmo-series-b">Series B</a></li>
      <li><a href="/fractional-cmo-bootstrapped-companies">Bootstrapped</a></li>
      <li><a href="/fractional-cmo-pe-backed-companies">PE-Backed</a></li>
      <li><a href="/fractional-cmo-venture-capital">VC-Backed</a></li>
      <li><a href="/best-fractional-cmo">Best Fractional CMO</a></li>
    </ul></div>

    <div class="footer-col"><h4>Industries</h4><ul>
      <li><a href="/fractional-cmo-saas">SaaS</a></li>
      <li><a href="/fractional-cmo-healthcare">Healthcare</a></li>
      <li><a href="/fractional-cmo-fintech">Fintech</a></li>
      <li><a href="/fractional-cmo-ai">AI Companies</a></li>
      <li><a href="/fractional-cmo-b2b">B2B</a></li>
      <li><a href="/fractional-cmo-ecommerce">eCommerce</a></li>
      <li><a href="/industries">All Industries</a></li>
    </ul></div>

    <div class="footer-col"><h4>Cities</h4><ul>
      <li><a href="/fractional-cmo-dallas-fort-worth">Dallas-Fort Worth</a></li>
      <li><a href="/fractional-cmo-greater-houston">Houston</a></li>
      <li><a href="/fractional-cmo-greater-chicago">Chicago</a></li>
      <li><a href="/fractional-cmo-greater-atlanta">Atlanta</a></li>
      <li><a href="/fractional-cmo-greater-miami">Miami</a></li>
      <li><a href="/fractional-cmo-greater-boston">Boston</a></li>
      <li><a href="/fractional-cmo-near-me">CMO Near Me</a></li>
    </ul></div>

    <div class="footer-col"><h4>Learn</h4><ul>
      <li><a href="/magnet-framework" style="color:var(--accent,#C9A84C);font-weight:600;">MAGNET Framework&trade;</a></li>
      <li><a href="/blog">Insights &amp; Blog</a></li>
      <li><a href="/about">About Mark</a></li>
      <li><a href="/testimonials">Testimonials</a></li>
      <li><a href="/faq">FAQ</a></li>
      <li><a href="/contact">Contact</a></li>
      <li><a href="https://academy.markcmo.com" target="_blank" style="color:var(--accent,#C9A84C);font-weight:600;">Academy &#x2197;</a></li>
    </ul></div>
  </div>

  <div class="footer-bar">
    <span class="footer-copy">&copy; 2026 Mark Gabrielli &middot; markcmo.com &middot; All rights reserved.</span>
    <div class="footer-bar-links">
      <a href="https://www.linkedin.com/in/marklgabrielli/" target="_blank" rel="noopener">LinkedIn</a>
      <a href="https://x.com/markgcmo" target="_blank" rel="noopener">X / Twitter</a>
      <a href="https://medium.com/@mark_louis_gabrielli_jr" target="_blank" rel="noopener">Medium</a>
      <a href="https://www.tiktok.com/@mark.gabrielli.cmo" target="_blank" rel="noopener">TikTok</a>
    </div>
  </div>
</footer>
`;

/** Just the <footer>…</footer> element — used to REPLACE old footer-mega blocks */
export const SITE_FOOTER_ELEMENT = `<footer>
  <div class="footer-main">
    <div class="footer-brand">
      <div class="footer-logo-text">Mark <span>Gabrielli</span></div>
      <p class="footer-about">Fractional CMO, COO &amp; Executive Consultant. I help businesses from $1M to $100M find what&rsquo;s broken, build what scales, and execute what others only talk about.</p>
      <div class="footer-chips">
        <span class="footer-chip">WETYR Founder</span>
        <span class="footer-chip">Fractional C-Suite</span>
        <span class="footer-chip">AI Strategist</span>
        <span class="footer-chip">CST Certified</span>
      </div>
      <div class="footer-socials">
        <a href="https://www.linkedin.com/in/marklgabrielli/" target="_blank" rel="noopener" class="footer-soc">in</a>
        <a href="mailto:mark@markcmo.com" class="footer-soc">@</a>
      </div>
    </div>

    <div class="footer-col"><h4>C-Suite</h4><ul>
      <li><a href="/fractional-cmo">Fractional CMO</a></li>
      <li><a href="/fractional-coo">Fractional COO</a></li>
      <li><a href="/fractional-ceo">Fractional CEO</a></li>
      <li><a href="/fractional-cto">Fractional CTO</a></li>
      <li><a href="/fractional-cfo">Fractional CFO</a></li>
      <li><a href="/executive-advisory">Executive Advisory</a></li>
      <li><a href="/services">All Services</a></li>
    </ul></div>

    <div class="footer-col"><h4>Marketing</h4><ul>
      <li><a href="/demand-generation">Demand Generation</a></li>
      <li><a href="/lead-generation">Lead Generation</a></li>
      <li><a href="/b2b-marketing">B2B Marketing</a></li>
      <li><a href="/content-marketing">Content Marketing</a></li>
      <li><a href="/email-marketing">Email Marketing</a></li>
      <li><a href="/digital-marketing">Digital Marketing</a></li>
      <li><a href="/social-media-marketing">Social Media</a></li>
      <li><a href="/linkedin-marketing">LinkedIn Marketing</a></li>
      <li><a href="/paid-social">Paid Social</a></li>
      <li><a href="/ppc-management">PPC Management</a></li>
      <li><a href="/local-seo">Local SEO</a></li>
      <li><a href="/crm-automation">CRM Automation</a></li>
      <li><a href="/marketing-automation">Marketing Automation</a></li>
      <li><a href="/account-based-marketing">ABM</a></li>
      <li><a href="/go-to-market-strategy">Go-to-Market</a></li>
      <li><a href="/marketing-strategy">Marketing Strategy</a></li>
    </ul></div>

    <div class="footer-col"><h4>Compare</h4><ul>
      <li><a href="/fractional-cmo-cost">CMO Cost</a></li>
      <li><a href="/compare/fractional-cmo-vs-full-time-cmo/">vs Full-Time CMO</a></li>
      <li><a href="/compare/fractional-cmo-vs-marketing-agency/">vs Agency</a></li>
      <li><a href="/compare/fractional-cmo-vs-vp-of-marketing/">vs VP of Marketing</a></li>
      <li><a href="/compare/fractional-cmo-vs-consultant/">vs Consultant</a></li>
      <li><a href="/compare/fractional-cmo-vs-interim-cmo/">vs Interim CMO</a></li>
      <li><a href="/chief-outsiders-alternative">Chief Outsiders Alt.</a></li>
    </ul></div>

    <div class="footer-col"><h4>By Stage</h4><ul>
      <li><a href="/fractional-cmo-pre-revenue">Pre-Revenue</a></li>
      <li><a href="/fractional-cmo-series-a">Series A</a></li>
      <li><a href="/fractional-cmo-series-b">Series B</a></li>
      <li><a href="/fractional-cmo-bootstrapped-companies">Bootstrapped</a></li>
      <li><a href="/fractional-cmo-pe-backed-companies">PE-Backed</a></li>
      <li><a href="/fractional-cmo-venture-capital">VC-Backed</a></li>
      <li><a href="/best-fractional-cmo">Best Fractional CMO</a></li>
    </ul></div>

    <div class="footer-col"><h4>Industries</h4><ul>
      <li><a href="/fractional-cmo-saas">SaaS</a></li>
      <li><a href="/fractional-cmo-healthcare">Healthcare</a></li>
      <li><a href="/fractional-cmo-fintech">Fintech</a></li>
      <li><a href="/fractional-cmo-ai">AI Companies</a></li>
      <li><a href="/fractional-cmo-b2b">B2B</a></li>
      <li><a href="/fractional-cmo-ecommerce">eCommerce</a></li>
      <li><a href="/industries">All Industries</a></li>
    </ul></div>

    <div class="footer-col"><h4>Cities</h4><ul>
      <li><a href="/fractional-cmo-dallas-fort-worth">Dallas-Fort Worth</a></li>
      <li><a href="/fractional-cmo-greater-houston">Houston</a></li>
      <li><a href="/fractional-cmo-greater-chicago">Chicago</a></li>
      <li><a href="/fractional-cmo-greater-atlanta">Atlanta</a></li>
      <li><a href="/fractional-cmo-greater-miami">Miami</a></li>
      <li><a href="/fractional-cmo-greater-boston">Boston</a></li>
      <li><a href="/fractional-cmo-near-me">CMO Near Me</a></li>
    </ul></div>

    <div class="footer-col"><h4>Learn</h4><ul>
      <li><a href="/magnet-framework" style="color:var(--accent,#C9A84C);font-weight:600;">MAGNET Framework&trade;</a></li>
      <li><a href="/blog">Insights &amp; Blog</a></li>
      <li><a href="/about">About Mark</a></li>
      <li><a href="/testimonials">Testimonials</a></li>
      <li><a href="/faq">FAQ</a></li>
      <li><a href="/contact">Contact</a></li>
      <li><a href="https://academy.markcmo.com" target="_blank" style="color:var(--accent,#C9A84C);font-weight:600;">Academy &#x2197;</a></li>
    </ul></div>
  </div>

  <div class="footer-bar">
    <span class="footer-copy">&copy; 2026 Mark Gabrielli &middot; markcmo.com &middot; All rights reserved.</span>
    <div class="footer-bar-links">
      <a href="https://www.linkedin.com/in/marklgabrielli/" target="_blank" rel="noopener">LinkedIn</a>
      <a href="https://x.com/markgcmo" target="_blank" rel="noopener">X / Twitter</a>
      <a href="https://medium.com/@mark_louis_gabrielli_jr" target="_blank" rel="noopener">Medium</a>
      <a href="https://www.tiktok.com/@mark.gabrielli.cmo" target="_blank" rel="noopener">TikTok</a>
    </div>
  </div>
</footer>`;
